wayk-1882: Add DenRouterKeepAliveInterval parameter
Devolutions/WaykBastion-ps pull request #17
Opened 2021-02-10 20:37 UTC by fdubois1

2021-02-11 21:14 UTC, awakecoding commented on WaykBastion/Public/WaykBastionConfig.ps1
> +    [int] $DenRouterKeepAliveInterval
Je renommerais a DenKeepAliveInterval, le "routeur" a pas besoin d'etre exposé à l'utilisateur tel quel.

2021-02-11 21:14 UTC, awakecoding requested changes
tu peux garder le meme nom dans le code de wayk den, mais dans le module je renommerais à DenKeepAliveInterval

2021-02-12 13:39 UTC, fdubois1 commented on WaykBastion/Public/WaykBastionConfig.ps1
> +    [int] $DenRouterKeepAliveInterval
Done. J'ai renommé, j'ai aussi mis à jour le changelog avec les changements faits.

2021-02-12 16:19 UTC, awakecoding approved these changes
LGTM

2021-02-12 16:19 UTC, merged